#!/bin/bash

digits="${1}"

if ! grep -qE '^[0-9]+$' <<< "${digits}"; then
  echo "Specify a number of digits." >&2
  echo "  ${0} <digits>" >&2
  exit 1
fi

i=0
while test "${i}" -lt "${digits}"; do 
  rn="$(
    dd bs=1 count=1 if=/dev/urandom 2>&- \
    | od -t d8 \
    | head -n 1 \
    | awk '{print $2}'
  )"
  if test "${rn}" -lt 7; then 
    continue
  fi
  echo -n "$(( rn % 10 ))"
  i="$(( i + 1 ))"
done
echo
